name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.24'
        - '1.23'
        - '1.22'
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Go ${{ matrix.go }} test 
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Get dependencies
      run:
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Bench
      run: make bench
